services:
  - type: web
    name: prd-for-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: USE_MYSQL
        value: "true"
      - key: MYSQL_HOST
        value: "bdm721874380.my3w.com"
      - key: MYSQL_PORT
        value: "3306"
      - key: MYSQL_DATABASE
        value: "bdm721874380_db"
      - key: MYSQL_USER
        value: "bdm721874380"
      - key: MYSQL_PASSWORD
        value: "i3L4M5eUBxCq@Pv"
      - key: DIFY_API_KEY
        value: "app-5zA5RoIpzA3isrshEQnWbvmq"
      - key: DIFY_API_BASE
        value: "http://teach.excelmaster.ai/v1"
      - key: DIFY_API_CHANNEL
        value: "chat"
      - key: JWT_SECRET_KEY
        value: "your-super-secret-jwt-key-change-in-production"
